language: python
dist: trusty
notifications:
  email: false
python:
  - "2.7"
sudo: required
before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -y install libnacl-dev libffi-dev haveged liberasurecode-dev
install: 
  - pip install pytest
  - python setup.py install

# command to run tests
script: 
  - python -m pytest